<?php

namespace Tests\Unit;

use App\Models\File;
use App\Models\FileStore;
use Illuminate\Http\UploadedFile;
use Tests\TestCase;

class FileStoreTest extends TestCase
{
    protected $file;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $file = new UploadedFile('./test_files/db1.sql', 'db7.sql', 'application/sql');
        $this->file = new FileStore($file);
    }

//    public function test_save() : void
//    {
//        $this->assertInstanceOf(File::class, $this->file->save());
//    }
}
