<?php

namespace Tests\Unit;

use App\Models\File;
use Illuminate\Http\UploadedFile;
use Tests\TestCase;
use App\Models\FileValidation;

class FileValidationTest extends TestCase
{
    protected $fileCorrect;
    protected $fileUnCorrect;
    protected $file;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->fileCorrect = new UploadedFile('./test_files/db1.sql', 'db1.sql', 'application/sql');
        $this->fileUnCorrect = new UploadedFile('./test_files/readme.txt', 'readme.txt', 'application/txt');
    }

    public function test_correct_checkType()
    {
        FileValidation::checkType($this->fileCorrect);
        $this->assertEmpty(FileValidation::$errors);
    }

    public function test_uncorrect_checkUnique()
    {
        FileValidation::checkUnique($this->fileUnCorrect);
        $this->assertEmpty(FileValidation::$errors);
    }

    public function test_uncorrect_checkType()
    {
        FileValidation::checkType($this->fileUnCorrect);
        $this->assertNotEmpty(FileValidation::$errors);
    }


    public function test_correct_checkUnique()
    {
        FileValidation::checkUnique($this->fileCorrect);
        $this->assertNotEmpty(FileValidation::$errors);
    }
}
